// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzrrycacclufrrdvazut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cnJ5Y2FjY2x1ZnJyZHZhenV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTk2MzEsImV4cCI6MjA2NjE3NTYzMX0.7PV8KEWASaybICycCz23MYil0JWnvgQ0KAqbnKudepE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);